queries_util = {
    /** Autentication Query */
    loginAutentication: 'SELECT * FROM INVENTIOLITE.USER WHERE USERNAME = ? AND PASSWORD = ?',
    /** Products CRUD */
    getProducts: 'SELECT * FROM INVENTIOLITE.PRODUCT',
    getProductById: 'SELECT * FROM INVENTIOLITE.PRODUCT WHERE ID = ?',
    getProductByCategory: 'SELECT * FROM INVENTIOLITE.PRODUCT WHERE CATEGORY_ID = ?',
    getActiveProducts: 'SELECT * FROM INVENTIOLITE.PRODUCT WHERE IS_ACTIVE = 1',
    getProductByUser: 'SELECT * FROM INVENTIOLITE.PRODUCT WHERE USER_ID = ?',
    updateProduct: 'UPDATE INVENTIOLITE.PRODUCT SET IMAGE=?, BARCODE=?, NAME=?, DESCRIPTION=?, INVENTARY_MIN=?, PRICE_IN=?, PRICE_OUT=?, UNIT=?, PRESENTATION=?, CATEGORY_ID=? WHERE ID=?',
    insertProduct: 'INSERT INTO INVENTIOLITE.PRODUCT (IMAGE, BARCODE, NAME, DESCRIPTION, INVENTARY_MIN, PRICE_IN, PRICE_OUT, UNIT, PRESENTATION, USER_ID, CATEGORY_ID, CREATED_AT) VALUES(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, CURRENT_DATE)',
    disableProduct: 'UPDATE INVENTIOLITE.PRODUCT SET IS_ACTIVE = ? WHERE ID = ?',
    /** Category CRUD */
    getCategory: 'SELECT * FROM INVENTIOLITE.CATEGORY',
    getCategoryById: 'SELECT * FROM INVENTIOLITE.CATEGORY WHERE ID=?',
    insertCategory: 'INSERT INTO INVENTIOLITE.CATEGORY (IMAGE, NAME, DESCRIPTION, CREATED_AT) VALUES(?, ?, ?, CURRENT_DATE)',
    updateCategory: 'UPDATE INVENTIOLITE.CATEGORY SET IMAGE=?, NAME=?, DESCRIPTION=? WHERE ID=?'

}

module.exports = queries_util;